### ISSUE TITLE
Fresh install not working,

### ISSUE THREAD

**Issue by Sanman96** [quatanium/python-onvif#29]
I am using Ubuntu 14.04 LTS (fresh install)
I installed pip and then used pip to install onvif as stated on the homepage.
I downloaded the wsdl file and xsd file straight form ONVIF.
When I launch python I typed

> from onvif import ONVIFCamera

then

> mycam = ONVIFCamera('IP_ADDR', 8088, 'admin', 'test', '')

i get 

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 227, in **init**
>     self.update_xaddrs()
>   File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 237, in update_xaddrs
>     services = self.devicemgmt.GetServices({'IncludeCapability': False})
>   File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 187, in **getattr**
>     return self.service_wrapper(getattr(self.ws_client.service, name))
>   File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 296, in **getattr**
>     port = self.__find(0)
>   File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 331, in __find
>     raise Exception, 'No services defined'
> Exception: No services defined

I have the files where it is looking for them (/etc/onvif/wsdl/devicemgmt.wsdl and /ver10/schema/onvif.xsd)

If I use the interactive cli with

> onvif-cli devicemgmt GetHostname --user 'admin' --password 'test' --host 'IPADDR' --port 8088

i get

> Traceback (most recent call last):
>   File "/usr/local/bin/onvif-cli", line 9, in <module>
>     load_entry_point('onvif==0.1.3', 'console_scripts', 'onvif-cli')()
>   File "/usr/local/lib/python2.7/dist-packages/onvif/cli.py", line 160, in main
>     cli.setup(args)
>   File "/usr/local/lib/python2.7/dist-packages/onvif/cli.py", line 39, in setup
>     args.wsdl, encrypt=args.encrypt)
>   File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 227, in **init**
>     self.update_xaddrs()
>   File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 237, in update_xaddrs
>     services = self.devicemgmt.GetServices({'IncludeCapability': False})
>   File "/usr/local/lib/python2.7/dist-packages/onvif/client.py", line 187, in **getattr**
>     return self.service_wrapper(getattr(self.ws_client.service, name))
>   File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 296, in **getattr**
>     port = self.__find(0)
>   File "/usr/local/lib/python2.7/dist-packages/suds/client.py", line 331, in __find
>     raise Exception, 'No services defined'
> Exception: No services defined

Even though there are plenty of services declared in the onvif wsdl, why isn't the program recognizing it? I am new to onvif and trying to learn it as fast as possible and I thought this library would be the perfect start.

If it is any help I am trying to interface to a group of AVIGILON 2.0MP Day/Night 20x HD PTZ Dome Cameras.

**Comment by paganlord** [comment]
I have the exact same issue. BTW, over a year and no answer at all??

**Comment by Sanman96** [comment]
I gave up on this library for having basically no support. I decided to use camera API's instead of using ONVIF.

**Comment by fpoulain** [comment]
For the record: I got the same problem while searching for and symlinking wsdl stuff. By default pip put it in /usr/local/wsdl/ then this worked:
```bash
onvif-cli --user 'admin' --password 'passwd' --host 'xx.xx.xx.xx' --port 80 -w /usr/local/wsdl/<<EOF
cmd devicemgmt GetCapabilities
EOF
```

**Comment by Sanman96** [comment]
Eventually I needed ONVIF compliance in my application so I ended up using a PHP ONVIF library. But I'm glad to see after almost 2 years someone finally answered it.
