### ISSUE TITLE
How to get remotediscovery service?

### ISSUE THREAD

**Issue by pmarkiewicz** [quatanium/python-onvif#6]
I'd liek to discovery cameras but cannot find how to get instance of remotediscovery

**Comment by sinchb** [comment]
Sorry, there is no remotediscovery in this project. You should pass the host and port of the camera to initialize Onvif. [Here](https://github.com/hlamer/python-ws-discovery) may be what you want.

**Comment by pmarkiewicz** [comment]
ok, thanks a lot

regards

2015-06-02 4:04 GMT+02:00 sinchb <notifications@github.com>:
