### ISSUE TITLE
How to find all Onvif devices on the network?

### ISSUE THREAD

**Issue by xanview** [quatanium/python-onvif#7]
I'm not sure if this is possible or not but it would be great to have a way to find all Onvif devices on the network.

**Comment by sinchb** [comment]
@hackeron This [lib](https://github.com/hlamer/python-ws-discovery) is what you want.

**Comment by sinchb** [comment]
does it work for you? @hackeron

**Comment by pylover** [comment]
Just use a network-scanner, such as python-nmap

**Comment by hackeron** [comment]
@sinchb I haven't tried it yet, but seems the library was last updated 2 years ago, is there anything better maintained?

@pylover Network scanning is often not possible as many IP cameras come with static IPs on various weird addresses. Some are 192.0.0.64, some are 192.168.1.100, others are 10.0.0.50, other still are 192.1.0.60, etc, etc.

**Comment by sinchb** [comment]
@pylover I suggest you to have a try  : )

**Comment by pylover** [comment]
@hackeron, I suggest u to take a TCP/IP tour. At all, you have to put all the cameras in a network to allow communicate each other. or using a router to introduce and make a way to nodes see each other

**Comment by hackeron** [comment]
@pylover What I am looking for is a solution to put all the camera in a network. Since many cameras come with static IP, I assume the only way of discovering them (other than using the manufacturer's windows software each time), is to use ws-discovery.

Once discovered, they have be reconfigured to either DHCP or other static IPs.

**Comment by pylover** [comment]
you have to configure the Network in interface in many network you guess 
may a camera exists. it means assign more than one ip address on your 
network adapter, then scanning all networks with python-nmap. to find 
the cameras ip addresses.
then connect to them using onevif and change whatever you want on 
device, such as ip address and gateway, etc.

**Comment by pylover** [comment]
Currently i am using python-nmap to discover cameras in my very own home-automation application. but just a single network i have. it's good enough to do something we are want.

**Comment by hackeron** [comment]
@pylover right, so you need to change your interface IP to 192.0.0.100 for example, and then use nmap to see if a camera exists. Unfortunately, you would need to change your interface IP many many times for all different kinds of IP cameras. This is a very slow and impractical solution.

From what I understand ws-discovery finds what the IP of the camera is, so you know exactly what to change your interface IP to, saving you time trying to guess and also finding the camera as soon as it is plugged in, without the delay of scanning the network (because it broadcasts this information).

**Comment by pylover** [comment]
Yes, because ARP request broadcasting require at least a route to a network/subnet.

**Comment by pylover** [comment]
you may try to discover your networks in multi-threaded manner, so you can scan networks, each in a separate thread simultaneously.

**Comment by hackeron** [comment]
@pylover from Wikipedia: "Web Services Dynamic Discovery (WS-Discovery) is a technical specification that defines a multicast discovery protocol to locate services on a local network. It operates over TCP and UDP port 3702 and uses IP multicast address 239.255.255.250"

So you do not need to be on the same network/subnet and you do not need to try to somehow get access to the switch/router ARP table, which is often not easily accessible.

**Comment by pylover** [comment]
so, still you need to be in a same netwrok to connect to the camera

**Comment by hackeron** [comment]
@pylover right... but how do you find out what that network is? - other than guess...

**Comment by pylover** [comment]
As i know, there is no-way to do that. just use a network scanner.

**Comment by xanview** [comment]
I think this is outside of the scope of python-onvif, so closing :)

**Comment by ijunaid8088** [comment]
@xanview How you resolved this issue? what you did? I am in the same problem right now..

**Comment by xanview** [comment]
It's a combination of arp scanning, arp broadcasting, ws-discovering, finding unused IPs by checking IPs at random and joining each network and then network scanning after you've joined all the detected networks - good luck :)

**Comment by theplen** [comment]
What about packet sniffing while rebooting the cameras?  They usually send out some packets on their subnets but you don't need to be on that subnet if you are capturing packets promiscuously.

**Comment by ijunaid8989** [comment]
@theplen Have you tried anything??

**Comment by theplen** [comment]
@ijunaid8989  Are you asking have I ever used this technique to discover cameras and other devices without knowing their static ip?  Yes many times.

**Comment by ijunaid8989** [comment]
@theplen now I am asking how you have done it? any code snippet?

**Comment by theplen** [comment]
@ijunaid8989 I'm have only done with wireshark or other packet sniffing programs.   But that being said, you could write a python program that makes use of the libpcap library (https://pypi.org/project/libpcap/) to capture packets and discover devices.

**Comment by ssieb** [comment]
The camera I have broadcasts using mdns, avahi, zeroconf (whatever the official name is).  I used avahi-browse to see the messages.  That let me find its IP address even though the static address was on a different subnet.

**Comment by Lalitdodake** [comment]
I want to change the default gateway of my web cam , so i am using SetNetworkDefaultGateway() method provided by onvif, but it is not working. is there any issue with this method.
